# __NUMPY (Numerical Python)__

In [1]:
1+2

3

In [2]:
x = 2+3

In [3]:
x

5

ini bukan code

$\displaystyle \sqrt\frac{(\sum(x{i}-\mu)^2}{n}$

In [4]:
#import library

import numpy as np

In [5]:
my_list = [1,2,3]
my_list
print(my_list)

[1, 2, 3]


In [6]:
print(type(my_list))

<class 'list'>


In [7]:
my_array = np.array(my_list)

In [8]:
print(my_list)
print(my_array)

[1, 2, 3]
[1 2 3]


In [9]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
my_list2 = ['a', 'b', 'c', 4, 5]
my_array2 = np.array(my_list2)

print(my_list2)
print(my_array2)

['a', 'b', 'c', 4, 5]
['a' 'b' 'c' '4' '5']


In [11]:
print(my_list2[3])
print(my_array2[3])

4
4


In [12]:
print(type(my_list2[3]))
print(type(my_array2[3]))

<class 'int'>
<class 'numpy.str_'>


In [13]:
my_list3 = [1.0, 2.5, 4.5, 6, 7]
my_array3 = np.array(my_list3)

print(my_list3)
print(my_array3)

[1.0, 2.5, 4.5, 6, 7]
[1.  2.5 4.5 6.  7. ]


In [14]:
print(type(my_list3[3]))
print(type(my_array3[3]))

<class 'int'>
<class 'numpy.float64'>


### str < float < int

In [15]:
my_list

[1, 2, 3]

In [16]:
my_list4 = [2,3,4]

## operasi matematika menggunakan array

In [17]:
my_list + my_list4

[1, 2, 3, 2, 3, 4]

In [18]:
my_array4 = np.array(my_list4)
my_array4

array([2, 3, 4])

In [19]:
print(my_array4.shape)

(3,)


In [20]:
my_list + my_array4

array([3, 5, 7])

In [21]:
print(my_array4)
print(my_array4 + 3)

[2 3 4]
[5 6 7]


kalo pertambahan matrix, harus satu atau shapenya sama. Gak cuma pertambahan, tapi operasi matematika yg lain

## Operasi matematika (x) menggunakan array

In [22]:
print(my_array4, my_list)
print(my_array * my_list)

[2 3 4] [1, 2, 3]
[1 4 9]


In [23]:
print(my_array4, my_array)
print(my_array4 * my_array)

[2 3 4] [1 2 3]
[ 2  6 12]


## Array 2 dimensi

In [24]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
print(list_of_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [25]:
my_matrix = np.array(list_of_list)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


bentuknya matrix 3x3, bisa dilakukan operasi matematika

## Operasi Matematika dengan array 2 dimensi

In [26]:
print(my_matrix)
print(my_matrix + 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
print(my_matrix + list_of_list)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [28]:
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
list_of_list[2][2]

9

## __INDEXING & SLICING__

### - 1 DIMENSI

In [30]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [31]:
#indexing
print(a[4])
print(a[-1])

14
15


In [32]:
#slicing 
##(start:stop)
print(a[1:3])
##(start:stop:step)
print(a[::2])

[11 12]
[10 12 14]


### - 2 DIMENSI 

In [33]:
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#indexing (row index, row column)
#mengambil value 6
print(my_matrix[1,2])
#sama saja
print(my_matrix[1][2])

6
6


In [35]:
#slicing
# ([row , column])
print(my_matrix[0,:])
print(my_matrix[0,2:])
print(my_matrix[:,0])
print(my_matrix[:1,0])

print(my_matrix[0:2,0:2])
print(my_matrix[[0,2],0:2])

[1 2 3]
[3]
[1 4 7]
[1]
[[1 2]
 [4 5]]
[[1 2]
 [7 8]]


In [36]:
#membalik array (sama kayak membalik list)
print(my_matrix[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [37]:
list_of_list2 = [[10,11,12], [13,14,15]]
my_matrix2 = np.array(list_of_list2)
print(my_matrix2)

[[10 11 12]
 [13 14 15]]


In [38]:
#row #coloumn
my_matrix.shape

(3, 3)

pertambahan/operasi matematik lain -> matrix dengan dimenasi samaharus sama shape. Tapi kalo beda dimensi bisa ditambah (satu dimensi +dua dimensi).

In [39]:
my_array, my_matrix

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [40]:
my_array + my_matrix

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## __2. Built-in Method Numpy

## 2.1 np.arange

In [41]:
#kalo di python
ar1 = range(0,10)
list(ar1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
#numpy
nar1 = np.arange(0,10)
nar1
# print(np.arange(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
print(type(nar1))

<class 'numpy.ndarray'>


In [44]:
#python
ar2 = range(0,10,2)
list(ar2)

[0, 2, 4, 6, 8]

In [45]:
#numpy
nar2 = np.arange(0,10,2)
nar2

array([0, 2, 4, 6, 8])

#### Bikin arange jadi dua dimensi

In [46]:
print(np.arange(0,12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 2.2 np.zeros() & np.ones() 

jadi kayak buat template data nantinya tinggal update

In [47]:
zer1 = np.zeros(7)
zer1

array([0., 0., 0., 0., 0., 0., 0.])

In [48]:
zer2 = np.zeros((4,5))
zer2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
zer2.shape

(4, 5)

In [50]:
len(zer2)

4

In [51]:
one1 = np.ones(7)
one1

array([1., 1., 1., 1., 1., 1., 1.])

In [52]:
one2 = np.ones((4,2))
one2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## 2.3 np.linspace()

##membuat array dengan jarak antar data yang sama besar
mau bikin 100data, jadi mau diambil beberapa data yg jaraknya sama
(awal range, akhir range,jml data yg mau diambil)

In [53]:
lin1 = np.linspace(0,1000,101)
lin1

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,
        360.,  370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,
        450.,  460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,
        540.,  550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,
        630.,  640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,
        720.,  730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,
        810.,  820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,
        900.,  910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,
        990., 1000.])

In [54]:
lin2 = np.linspace(0,10,3)
lin2

array([ 0.,  5., 10.])

## 2.4 np.eye() & np.identity()

In [55]:
##membuat data yang dimana diagonalnya 1, dan sisanya 0
#kalo matriks simetris, hasilnya akan simetris. Begitupun sebaliknya

In [56]:
eye1 = np.eye(3, k=1)
eye1

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [57]:
eye2 = np.eye(3,2)
eye2

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [58]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [59]:
np.identity(2, dtype = str)

array([['1', ''],
       ['', '1']], dtype='<U1')

### 2.5 np.random.rand()

In [60]:
#membuat array dengan random value antara 0 -1 dengan data float

#seed = pseudo random generator, mengontrol randomizing. 
#Dan kalo di run lagi di nomer yg sama, tidak akan berubah
#kalo beda angka, baru berubah

In [61]:
np.random.seed(24)

rand1 = np.random.rand(10)
rand1

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 , 0.36105635,
       0.73984099, 0.99645573, 0.31634698, 0.13654458, 0.38398001])

In [62]:
rand2 = np.random.rand(5,5)
rand2

array([[0.32051928, 0.36641475, 0.70965156, 0.90014243, 0.53411544],
       [0.24729376, 0.67180656, 0.56172911, 0.54255988, 0.8934476 ],
       [0.84277955, 0.30601259, 0.63116978, 0.68023886, 0.97042756],
       [0.89356715, 0.94242586, 0.64222548, 0.61464763, 0.22768325],
       [0.48603187, 0.8072193 , 0.84422015, 0.53468087, 0.75779805]])

In [63]:
#intermezo
normal1 =np.random.normal(0,1,100)
normal1

array([ 1.19287519e+00, -1.10021085e-03,  9.90318015e-01,  3.27802060e-01,
       -5.12540806e-01, -1.40636025e+00, -9.98815116e-01,  3.48012510e-01,
       -2.18777665e-01, -9.92222900e-01,  6.76690181e-01,  8.72009137e-02,
        1.53894538e+00, -5.89839719e-01,  3.34284857e-01,  6.51931540e-01,
        1.60774248e-01, -8.81227234e-01,  2.44670492e-01,  1.28596301e+00,
        6.04934551e-01, -2.07538966e+00, -4.81376250e-01, -1.75180743e+00,
        6.03821744e-01, -1.50176355e+00, -1.27990816e+00,  8.86080499e-01,
        9.42286796e-01, -1.26932837e+00,  5.20933334e-01, -5.86559636e-01,
       -8.06896394e-02,  2.76513878e-01, -2.51783793e-01, -6.64441855e-01,
       -1.20578491e+00,  2.56341371e-01, -5.95081864e-01,  1.80285554e-01,
       -1.31960078e-01, -1.41435441e+00,  1.52324443e+00, -3.38449383e-01,
        7.05489161e-01, -1.52250603e+00, -1.44027274e+00,  2.28156831e-01,
        3.75322707e-01, -5.07393620e-01,  1.99525802e+00, -2.65319553e+00,
        1.61172047e-01,  

## 2.6 np.random.randint

In [64]:
##membuat data atau array dengan value random dan datanya berupa integer
#format 1dimensi : (awal range, akhir range, mencari berapa angka angka)
#format 2 dimensi : (awal range, akhir range, (row,coloumn))
#setiap run berubah

In [65]:
randint1 = np.random.randint(1,15)
randint1

1

In [66]:
randint2 = np.random.randint(1,15,10)
randint2

array([ 3, 13,  6,  1, 14, 12,  4, 14,  8, 13])

In [67]:
randint3 = np.random.randint(1,15,(5,5))
randint3

array([[10,  8,  2,  9, 14],
       [11, 12,  6,  6, 14],
       [ 6, 10, 12, 10, 12],
       [14,  6, 12,  2, 12],
       [ 3, 12,  7,  9, 10]])

### 2.7 np.reshape()

In [68]:
my_array5 = np.random.randint(1,10,20)
my_array5

array([5, 3, 7, 2, 1, 8, 3, 8, 8, 4, 7, 7, 7, 3, 7, 5, 5, 3, 8, 4])

In [69]:
my_array5.shape

(20,)

In [70]:
##mereshape jadi satu dimensi menjadi dimensi lain
#jadi kalo reshape, harus pasangan bilangan faktor dari shapenya
#misalnya shape20, reshape jadi 4,5

In [71]:
my_matrix5 = my_array5.reshape(4,5)
my_matrix5

array([[5, 3, 7, 2, 1],
       [8, 3, 8, 8, 4],
       [7, 7, 7, 3, 7],
       [5, 5, 3, 8, 4]])

In [72]:
my_matrix6 =  my_array5.reshape(2,2,5)
#(dimensi pertama, dimensi kedua, dimensi ketiga)
my_matrix6

array([[[5, 3, 7, 2, 1],
        [8, 3, 8, 8, 4]],

       [[7, 7, 7, 3, 7],
        [5, 5, 3, 8, 4]]])

In [73]:
my_matrix6.shape

(2, 2, 5)

In [74]:
##kalo datanya banyak
#format:row diserah kan ke numpy, coloumnya kita yg tentuin (-1,5)
#-1 => diserahkan ke numpy untuk diproses, tapi gabisa -1 dua2nya di coloum dan row
#harus salah satu ditentuin dulu

In [75]:
my_array6 = np.random.randint(1,10,125)
my_array6

array([6, 5, 8, 8, 9, 7, 7, 3, 5, 8, 7, 1, 9, 8, 3, 1, 2, 1, 2, 3, 4, 4,
       5, 9, 8, 2, 8, 3, 4, 4, 7, 8, 8, 2, 5, 5, 6, 1, 2, 4, 4, 1, 1, 2,
       3, 1, 4, 2, 7, 1, 2, 5, 1, 8, 3, 4, 9, 9, 5, 1, 3, 8, 9, 9, 3, 5,
       9, 8, 1, 1, 4, 8, 3, 9, 1, 3, 6, 3, 6, 1, 8, 6, 9, 4, 8, 5, 6, 3,
       3, 7, 8, 5, 1, 9, 8, 6, 8, 7, 8, 3, 3, 1, 3, 7, 2, 6, 5, 1, 5, 8,
       1, 9, 8, 9, 8, 5, 8, 4, 5, 6, 9, 5, 6, 9, 2])

In [76]:
my_matrix7 = my_array6.reshape(-1,5)
my_matrix7

array([[6, 5, 8, 8, 9],
       [7, 7, 3, 5, 8],
       [7, 1, 9, 8, 3],
       [1, 2, 1, 2, 3],
       [4, 4, 5, 9, 8],
       [2, 8, 3, 4, 4],
       [7, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [4, 1, 1, 2, 3],
       [1, 4, 2, 7, 1],
       [2, 5, 1, 8, 3],
       [4, 9, 9, 5, 1],
       [3, 8, 9, 9, 3],
       [5, 9, 8, 1, 1],
       [4, 8, 3, 9, 1],
       [3, 6, 3, 6, 1],
       [8, 6, 9, 4, 8],
       [5, 6, 3, 3, 7],
       [8, 5, 1, 9, 8],
       [6, 8, 7, 8, 3],
       [3, 1, 3, 7, 2],
       [6, 5, 1, 5, 8],
       [1, 9, 8, 9, 8],
       [5, 8, 4, 5, 6],
       [9, 5, 6, 9, 2]])

## 2.8 arr.max() & arr.argmax

In [77]:
#arr.max = mencari nilai terbesar dari array, dan mengembalikan dengan value
#arr.argmax = mencari index nilai terbesar dari array (yg pertama kali ditemui)

In [78]:
my_matrix7.max()

9

In [79]:
my_matrix7.argmax()

4

## FLATEN() VS RAVEL()

In [80]:
#flatten = seperti copy, ravel = hanya view saja
# a = [1,2,3]
# a = b ==> ravel
# c = a.copy() ==> flatten

flat = my_matrix7.flatten()
ravel = my_matrix7.ravel()

In [81]:
ravel[0] = 1
print(ravel)
print(my_matrix7)

[1 5 8 8 9 7 7 3 5 8 7 1 9 8 3 1 2 1 2 3 4 4 5 9 8 2 8 3 4 4 7 8 8 2 5 5 6
 1 2 4 4 1 1 2 3 1 4 2 7 1 2 5 1 8 3 4 9 9 5 1 3 8 9 9 3 5 9 8 1 1 4 8 3 9
 1 3 6 3 6 1 8 6 9 4 8 5 6 3 3 7 8 5 1 9 8 6 8 7 8 3 3 1 3 7 2 6 5 1 5 8 1
 9 8 9 8 5 8 4 5 6 9 5 6 9 2]
[[1 5 8 8 9]
 [7 7 3 5 8]
 [7 1 9 8 3]
 [1 2 1 2 3]
 [4 4 5 9 8]
 [2 8 3 4 4]
 [7 8 8 2 5]
 [5 6 1 2 4]
 [4 1 1 2 3]
 [1 4 2 7 1]
 [2 5 1 8 3]
 [4 9 9 5 1]
 [3 8 9 9 3]
 [5 9 8 1 1]
 [4 8 3 9 1]
 [3 6 3 6 1]
 [8 6 9 4 8]
 [5 6 3 3 7]
 [8 5 1 9 8]
 [6 8 7 8 3]
 [3 1 3 7 2]
 [6 5 1 5 8]
 [1 9 8 9 8]
 [5 8 4 5 6]
 [9 5 6 9 2]]


In [82]:
flat[0] = 1
print(flat)
print(my_matrix7)

[1 5 8 8 9 7 7 3 5 8 7 1 9 8 3 1 2 1 2 3 4 4 5 9 8 2 8 3 4 4 7 8 8 2 5 5 6
 1 2 4 4 1 1 2 3 1 4 2 7 1 2 5 1 8 3 4 9 9 5 1 3 8 9 9 3 5 9 8 1 1 4 8 3 9
 1 3 6 3 6 1 8 6 9 4 8 5 6 3 3 7 8 5 1 9 8 6 8 7 8 3 3 1 3 7 2 6 5 1 5 8 1
 9 8 9 8 5 8 4 5 6 9 5 6 9 2]
[[1 5 8 8 9]
 [7 7 3 5 8]
 [7 1 9 8 3]
 [1 2 1 2 3]
 [4 4 5 9 8]
 [2 8 3 4 4]
 [7 8 8 2 5]
 [5 6 1 2 4]
 [4 1 1 2 3]
 [1 4 2 7 1]
 [2 5 1 8 3]
 [4 9 9 5 1]
 [3 8 9 9 3]
 [5 9 8 1 1]
 [4 8 3 9 1]
 [3 6 3 6 1]
 [8 6 9 4 8]
 [5 6 3 3 7]
 [8 5 1 9 8]
 [6 8 7 8 3]
 [3 1 3 7 2]
 [6 5 1 5 8]
 [1 9 8 9 8]
 [5 8 4 5 6]
 [9 5 6 9 2]]


## np.all() dan np.any()

np.all() = mengecek tidak adanya nol
np.any() = mengecek adanya element bukan nol

In [83]:
x = np.array([1,2,3,4])
y = np.array([1,2,3,0])
z = np.array([0,0,0,0])

print(np.all(x))
print(np.all(y))
print(np.all(z))
print(np.any(x))
print(np.any(y))
print(np.any(z))

True
False
False
True
True
False


## 2.9 arr.min() & arr.argmin()

arr.min() = mencari nilai terkecil
arr.argmin() = mencari index nilai terkecil yg muncul pertama kali

In [91]:
print(my_matrix7)

[[1 5 8 8 9]
 [7 7 3 5 8]
 [7 1 9 8 3]
 [1 2 1 2 3]
 [4 4 5 9 8]
 [2 8 3 4 4]
 [7 8 8 2 5]
 [5 6 1 2 4]
 [4 1 1 2 3]
 [1 4 2 7 1]
 [2 5 1 8 3]
 [4 9 9 5 1]
 [3 8 9 9 3]
 [5 9 8 1 1]
 [4 8 3 9 1]
 [3 6 3 6 1]
 [8 6 9 4 8]
 [5 6 3 3 7]
 [8 5 1 9 8]
 [6 8 7 8 3]
 [3 1 3 7 2]
 [6 5 1 5 8]
 [1 9 8 9 8]
 [5 8 4 5 6]
 [9 5 6 9 2]]


In [93]:
my_matrix7.min()

1

In [95]:
#index nilai terkecil yang pertama kali ditemui ada di index
my_matrix7.argmin()

0

## 2.10 arr.dtype(), type(), array.astype()

In [223]:
my_matrix7

array([[1, 5, 8, 8, 9],
       [7, 7, 3, 5, 8],
       [7, 1, 9, 8, 3],
       [1, 2, 1, 2, 3],
       [4, 4, 5, 9, 8],
       [2, 8, 3, 4, 4],
       [7, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [4, 1, 1, 2, 3],
       [1, 4, 2, 7, 1],
       [2, 5, 1, 8, 3],
       [4, 9, 9, 5, 1],
       [3, 8, 9, 9, 3],
       [5, 9, 8, 1, 1],
       [4, 8, 3, 9, 1],
       [3, 6, 3, 6, 1],
       [8, 6, 9, 4, 8],
       [5, 6, 3, 3, 7],
       [8, 5, 1, 9, 8],
       [6, 8, 7, 8, 3],
       [3, 1, 3, 7, 2],
       [6, 5, 1, 5, 8],
       [1, 9, 8, 9, 8],
       [5, 8, 4, 5, 6],
       [9, 5, 6, 9, 2]])

In [225]:
type(my_matrix7)

numpy.ndarray

In [96]:
my_matrix7.dtype

dtype('int32')

In [226]:
my_matrix7.astype(str)

array([['1', '5', '8', '8', '9'],
       ['7', '7', '3', '5', '8'],
       ['7', '1', '9', '8', '3'],
       ['1', '2', '1', '2', '3'],
       ['4', '4', '5', '9', '8'],
       ['2', '8', '3', '4', '4'],
       ['7', '8', '8', '2', '5'],
       ['5', '6', '1', '2', '4'],
       ['4', '1', '1', '2', '3'],
       ['1', '4', '2', '7', '1'],
       ['2', '5', '1', '8', '3'],
       ['4', '9', '9', '5', '1'],
       ['3', '8', '9', '9', '3'],
       ['5', '9', '8', '1', '1'],
       ['4', '8', '3', '9', '1'],
       ['3', '6', '3', '6', '1'],
       ['8', '6', '9', '4', '8'],
       ['5', '6', '3', '3', '7'],
       ['8', '5', '1', '9', '8'],
       ['6', '8', '7', '8', '3'],
       ['3', '1', '3', '7', '2'],
       ['6', '5', '1', '5', '8'],
       ['1', '9', '8', '9', '8'],
       ['5', '8', '4', '5', '6'],
       ['9', '5', '6', '9', '2']], dtype='<U11')

## 3. INDEXING & SLICING

In [99]:
#Kita buat array baru
my_array8 = np.arange(11,31)
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [101]:
#indexing sama seperti list python
my_array8[3]

14

In [105]:
#[start:stop]
my_array8[0:4]
#sama seperti list, batas belakang tidak diikutkan

array([11, 12, 13, 14])

In [104]:
#[start:stop:step]
my_array8[0:9:2]

array([11, 13, 15, 17, 19])

### 3.1 Len()

In [100]:
len(my_array8)

20

#### 2 dimensi

In [106]:
my_matrix8 = my_matrix7[:10].copy()
my_matrix8

array([[1, 5, 8, 8, 9],
       [7, 7, 3, 5, 8],
       [7, 1, 9, 8, 3],
       [1, 2, 1, 2, 3],
       [4, 4, 5, 9, 8],
       [2, 8, 3, 4, 4],
       [7, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [4, 1, 1, 2, 3],
       [1, 4, 2, 7, 1]])

In [108]:
my_matrix8[5]

array([2, 8, 3, 4, 4])

In [111]:
my_matrix8[4,2]

5

## 4. BROADCASTING

In [113]:
my_matrix8

array([[1, 5, 8, 8, 9],
       [7, 7, 3, 5, 8],
       [7, 1, 9, 8, 3],
       [1, 2, 1, 2, 3],
       [4, 4, 5, 9, 8],
       [2, 8, 3, 4, 4],
       [7, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [4, 1, 1, 2, 3],
       [1, 4, 2, 7, 1]])

In [114]:
#tentukan row dan column yg akan diganti [row , column]
my_matrix8[0,0:4] = 0
my_matrix8

array([[0, 0, 0, 0, 9],
       [7, 7, 3, 5, 8],
       [7, 1, 9, 8, 3],
       [1, 2, 1, 2, 3],
       [4, 4, 5, 9, 8],
       [2, 8, 3, 4, 4],
       [7, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [4, 1, 1, 2, 3],
       [1, 4, 2, 7, 1]])

In [119]:
my_matrix8[0:,0:1] = 5
my_matrix8

array([[5, 0, 0, 0, 9],
       [5, 7, 3, 5, 8],
       [5, 1, 9, 8, 3],
       [5, 2, 1, 2, 3],
       [5, 4, 5, 9, 8],
       [5, 8, 3, 4, 4],
       [5, 8, 8, 2, 5],
       [5, 6, 1, 2, 4],
       [5, 1, 1, 2, 3],
       [5, 4, 2, 7, 1]])

In [121]:
#bisa lgsg semua dengan beda angka tapi disiapkan angka sesuai len yg mau diganti.
my_matrix8[0:,0] = [1,2,3,4,5,6,7,8,9,10]
my_matrix8

array([[ 1,  0,  0,  0,  9],
       [ 2,  7,  3,  5,  8],
       [ 3,  1,  9,  8,  3],
       [ 4,  2,  1,  2,  3],
       [ 5,  4,  5,  9,  8],
       [ 6,  8,  3,  4,  4],
       [ 7,  8,  8,  2,  5],
       [ 8,  6,  1,  2,  4],
       [ 9,  1,  1,  2,  3],
       [10,  4,  2,  7,  1]])

### 4.1 np.where()

In [231]:
#mencari elemen di dua dimensi, hasilnya 2 array yaitu row dan column
#hasilnya berupa return
np.where(my_matrix8 > 8)

(array([0, 2, 4, 8, 9], dtype=int64), array([4, 2, 3, 0, 0], dtype=int64))

In [126]:
#1dimensi
np.where(my_array8<20)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [131]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [228]:
np.where(my_array8 == 11)

(array([0], dtype=int64),)

In [229]:
np.where(my_array8 == 5)

(array([], dtype=int64),)

In [130]:
#cari dan langsung ganti (broadcasting lebih mudah)
# np.where(kondisinya apa, value ketika kondisi sesuai, value ketika kondisi tidak sesuai)
#bisa diubah jadi string, tapi data type semua akan jadi string
my_array9 = np.where(my_array8<20,21,my_array8)
my_array9

array([21, 21, 21, 21, 21, 21, 21, 21, 21, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

## 5. arr.copy()

In [133]:
my_array9 = my_array8.copy()
my_array9

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [134]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [136]:
#tidak merubah parent
my_array9[0] = 100
print(my_array9)
print(my_array8)

[100  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


## 6. slicing 2d Array

In [138]:
my_matrix8

array([[ 1,  0,  0,  0,  9],
       [ 2,  7,  3,  5,  8],
       [ 3,  1,  9,  8,  3],
       [ 4,  2,  1,  2,  3],
       [ 5,  4,  5,  9,  8],
       [ 6,  8,  3,  4,  4],
       [ 7,  8,  8,  2,  5],
       [ 8,  6,  1,  2,  4],
       [ 9,  1,  1,  2,  3],
       [10,  4,  2,  7,  1]])

In [139]:
#[row awal:row akhir, column awal: index colum akhir]
my_matrix8[0:3, 2:]

array([[0, 0, 9],
       [3, 5, 8],
       [9, 8, 3]])

In [141]:
#bisa [start:stop:step]
my_matrix8[-3::1,0:2]

array([[ 8,  6],
       [ 9,  1],
       [10,  4]])

In [146]:
my_matrix8[-5:,0].reshape(-1,1)

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [143]:
my_matrix8[-3:,0:2]

array([[ 8,  6],
       [ 9,  1],
       [10,  4]])

In [145]:
my_matrix8[1:5,-1:]

array([[8],
       [3],
       [3],
       [8]])

## 7. Lenght of Array


In [147]:
my_matrix8

array([[ 1,  0,  0,  0,  9],
       [ 2,  7,  3,  5,  8],
       [ 3,  1,  9,  8,  3],
       [ 4,  2,  1,  2,  3],
       [ 5,  4,  5,  9,  8],
       [ 6,  8,  3,  4,  4],
       [ 7,  8,  8,  2,  5],
       [ 8,  6,  1,  2,  4],
       [ 9,  1,  1,  2,  3],
       [10,  4,  2,  7,  1]])

In [148]:
my_matrix8

array([[ 1,  0,  0,  0,  9],
       [ 2,  7,  3,  5,  8],
       [ 3,  1,  9,  8,  3],
       [ 4,  2,  1,  2,  3],
       [ 5,  4,  5,  9,  8],
       [ 6,  8,  3,  4,  4],
       [ 7,  8,  8,  2,  5],
       [ 8,  6,  1,  2,  4],
       [ 9,  1,  1,  2,  3],
       [10,  4,  2,  7,  1]])

In [149]:
len(my_matrix8)

10

In [150]:
my_matrix8.shape

(10, 5)

## 8. Selection Using COnditional Statement

In [152]:
gaji = np.random.randint(5,25,20)
gaji

array([ 7, 23, 10,  9, 24, 15,  7, 11, 10, 17,  7, 21, 24, 11,  5, 20,  9,
       10, 20,  5])

In [153]:
gaji > 10

array([False,  True, False, False,  True,  True, False,  True, False,
        True, False,  True,  True,  True, False,  True, False, False,
        True, False])

In [154]:
up_10 = gaji[gaji>10]
up_10

array([23, 24, 15, 11, 17, 21, 24, 11, 20, 20])

In [155]:
len(up_10)/len(gaji)*100

50.0

In [156]:
# ~ = inverse
~(gaji>10)

array([ True, False,  True,  True, False, False,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
       False,  True])

In [158]:
under_10 = gaji[~(gaji>10)]
under_10

array([ 7, 10,  9,  7, 10,  7,  5,  9, 10,  5])

In [160]:
#hampir sama kayak np.where, tapi np.where mereturn index
#kalo ini mereturn boolean

## 9. Aritmetic

In [162]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [164]:
my_array10 = np.random.randint(10,15,20)
my_array10

array([14, 11, 10, 10, 10, 14, 12, 11, 10, 11, 12, 10, 13, 10, 14, 12, 13,
       11, 13, 11])

In [165]:
my_array9 + my_array10

array([114,  23,  23,  24,  25,  30,  29,  29,  29,  31,  33,  32,  36,
        34,  39,  38,  40,  39,  42,  41])

In [166]:
my_matrix9 = my_array9.reshape(4,5)
my_matrix10 = my_array10.reshape(2,10)

In [167]:
my_matrix9

array([[100,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30]])

In [169]:
my_matrix10

array([[14, 11, 10, 10, 10, 14, 12, 11, 10, 11],
       [12, 10, 13, 10, 14, 12, 13, 11, 13, 11]])

In [175]:
#Gabisa dilakukan operasi matematika jika beda shape
#yang penting jumlah kolomnya sama

# my_matrix9+my_matrix10

In [176]:
my_array10[:5]

array([14, 11, 10, 10, 10])

In [172]:
my_matrix9 + my_array10[:5]

array([[114,  23,  23,  24,  25],
       [ 30,  28,  28,  29,  30],
       [ 35,  33,  33,  34,  35],
       [ 40,  38,  38,  39,  40]])

In [173]:
my_matrix9.shape

(4, 5)

In [174]:
my_array10[:5].shape

(5,)

In [234]:
my_matrix9 * my_array10[:5]

array([[1400,  132,  130,  140,  150],
       [ 224,  187,  180,  190,  200],
       [ 294,  242,  230,  240,  250],
       [ 364,  297,  280,  290,  300]])

In [ ]:
x = [11,12,13,14,15]
y = [1,2,3,4,5]

In [236]:
x + y

array([2, 4, 6, 4])

### np.power = pangkat

In [177]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [178]:
np.power(my_array9, [2])

array([10000,   144,   169,   196,   225,   256,   289,   324,   361,
         400,   441,   484,   529,   576,   625,   676,   729,   784,
         841,   900], dtype=int32)

### np.sqrt = akar pangkat 2

In [181]:
#display menampilkan hasil return aja, bukan diprint
display(my_array9)
np.sqrt(my_array9)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

array([10.        ,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558])

## np.log()

In [182]:
#pangkatan dua
np.log2(4)

2.0

In [184]:
#pangkatan sepuluh
np.log10(100)

2.0

In [185]:
np.exp(2)

7.38905609893065

In [186]:
np.mean(my_array9)

24.95

In [187]:
np.median(my_array9)

21.5

In [188]:
#std numpy, for population (n)
np.std(my_array8)

5.766281297335398

In [190]:
#std for sampel (n-1)
my_array8.std(ddof=1)

5.916079783099616

### np.absolute

In [192]:
np.absolute(-2)

2

In [193]:
np.sin(my_array9)

array([-0.50636564, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162])

In [194]:
np.cos(my_array9)

array([ 0.86231887,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145])

In [195]:
np.tan(my_array9)

array([-0.58721392, -0.63585993,  0.46302113,  7.24460662, -0.8559934 ,
        0.30063224,  3.49391565, -1.13731371,  0.15158947,  2.23716094,
       -1.52749853,  0.00885166,  1.58815308, -2.1348967 , -0.13352641,
        1.17875355, -3.2737038 , -0.2814296 ,  0.88714284, -6.4053312 ])

In [ ]:
##masih ada lagi

## 10. np.append(), np.insert(), np.delete()

In [ ]:
##mereturn sesuatu tapi gak mengubah array9 yg asli
#kalo mau dijadiin variabel

In [196]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [197]:
## menambah di belakang
#np.append(array,value)
np.append(my_array9,31)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31])

In [199]:
#menambah di sutu index
#np.insert(array, index, value)
np.insert(my_array9, 10,110)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20, 110,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [239]:
# np.delete(array, index)
np.delete(my_array9, 0)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

## 11. np.vstack() & np.htack()

In [202]:
#vstack = menumpuk data secara vertikal, menambah jadi atas bawah.
# perhatikan kolomnya harus sama.

#hstack = menumpuk data secara horisontal, menambah jadi kanan kiri.
# perhatikan barisnya harus sama dan dimensionnya.

In [203]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [204]:
my_array10

array([14, 11, 10, 10, 10, 14, 12, 11, 10, 11, 12, 10, 13, 10, 14, 12, 13,
       11, 13, 11])

In [205]:
vstack9_10 = np.vstack([my_array9, my_array10])
print(vstack9_10)

[[100  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
   29  30]
 [ 14  11  10  10  10  14  12  11  10  11  12  10  13  10  14  12  13  11
   13  11]]


In [206]:
vstack9_10.shape

(2, 20)

In [207]:
my_matrix11 = np.random.randint(1,10,[2,20])
my_matrix11

array([[3, 2, 9, 4, 7, 5, 4, 2, 1, 9, 4, 6, 3, 1, 8, 4, 2, 3, 7, 6],
       [9, 6, 8, 6, 5, 2, 6, 4, 7, 6, 6, 4, 4, 4, 5, 3, 7, 7, 7, 4]])

In [256]:
hstack9_10 = np.hstack([my_array9, my_array10])
hstack9_10

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  14,  11,  10,  10,  10,  14,
        12,  11,  10,  11,  12,  10,  13,  10,  14,  12,  13,  11,  13,
        11])

## 12. np.concatenate()

In [211]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [212]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [214]:
#axis=1 ==> nambah kesamping alias nambah colum 
arr8_9_0 = np.concatenate([my_array9, my_array8], axis=0)
arr8_9_0

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30])

In [257]:
arr8_9_1_ = np.concatenate([my_array9, my_array8], axis=1)
arr8_9_1_

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# axis=0 ==> nambah kebawah alias baris

In [251]:
arr8_9_1 = np.concatenate([my_array9.reshape(1,-1), my_array8.reshape(1,-1)], axis=0)
arr8_9_1

array([[100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30]])

In [216]:
##### ketinggalan

## 13. np.sort()

In [217]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [218]:
#mengurutkan dari kecil ke besar
np.sort(my_array9)

array([ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30, 100])

## 14. arr.transpose

In [220]:
my_matrix9

array([[100,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30]])

In [221]:
#Mengubah kolom jadi baris, baris jadi kolom
my_matrix9.transpose()

array([[100,  16,  21,  26],
       [ 12,  17,  22,  27],
       [ 13,  18,  23,  28],
       [ 14,  19,  24,  29],
       [ 15,  20,  25,  30]])

In [222]:
my_matrix9.T

array([[100,  16,  21,  26],
       [ 12,  17,  22,  27],
       [ 13,  18,  23,  28],
       [ 14,  19,  24,  29],
       [ 15,  20,  25,  30]])

In [243]:
zzz = np.array([[1,5,8,8,9],[7,7,3,5,8]])
zzz

array([[1, 5, 8, 8, 9],
       [7, 7, 3, 5, 8]])

In [244]:
zzz.T

array([[1, 7],
       [5, 7],
       [8, 3],
       [8, 5],
       [9, 8]])